spring:
  datasource:
    url: jdbc:mysql://172.16.14.2:23306/bio_cer_dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: canal
    password: CanalQibio2026_
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: 172.16.14.2:9092
    consumer:
      group-id: bio-drqi-es-canal
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

bio:
  es:
    enabled: true
    hosts:
      - http://172.16.14.2:9200
    # 如 ES 开启鉴权，取消注释
    username: elastic
    password: elastic123
    canal:
      enabled: true
      topic: project-search-topic
      group-id: bio-drqi-es-canal
