ALTER TABLE `seed_stock_in_log`
    ADD COLUMN `plant_code` varchar(64) NULL COMMENT '种植编号',
    ADD COLUMN `parent_num` varchar(64) NULL COMMENT '上一代种子编号',
    ADD COLUMN `father_info` varchar(255) NULL COMMENT '父本信息',
    ADD COLUMN `mather_info` varchar(255) NULL COMMENT '母本信息',
    ADD COLUMN `generation` varchar(16) NULL COMMENT '代次',
    ADD COLUMN `species_code` varchar(64) NULL COMMENT '项目物种',
    ADD COLUMN `breed_code` varchar(64) NULL COMMENT '品种',
    ADD COLUMN `pollination_method` varchar(255) NULL COMMENT '授粉方式',
    ADD COLUMN `harvest_type` varchar(255) NULL COMMENT '收获方式',
    ADD COLUMN `harvest_time` varchar(16) NULL COMMENT '收获时间',
    ADD COLUMN `production_location_code` varchar(255) NULL COMMENT '生产地点',
    ADD COLUMN `stock_location_num` varchar(255) NULL COMMENT '库位编号',
    ADD COLUMN `total_number` decimal(10,2) NULL COMMENT '入库时数量',
    ADD COLUMN `target_character` text NULL COMMENT '目标性状',
    ADD COLUMN `alias_name` varchar(255) NULL COMMENT '别名',
    ADD COLUMN `gene_type` varchar(255) NULL COMMENT '基因型',
    ADD COLUMN `material_type` varchar(255) NULL COMMENT '材料类型',
    ADD COLUMN `mather_seed_num` varchar(32) NULL COMMENT '母本种子编号',
    ADD COLUMN `father_seed_num` varchar(32) NULL COMMENT '父本种子编号',
    ADD COLUMN `mather_region_num` varchar(32) NULL COMMENT '母本小区编号',
    ADD COLUMN `father_region_num` varchar(32) NULL COMMENT '父本小区编号',
    ADD COLUMN `genealogy` varchar(255) NULL COMMENT '系谱',
    ADD COLUMN `gene_separate_flag` varchar(255) NULL COMMENT '是否基因分离',
    ADD COLUMN `trans_flag` varchar(255) NULL COMMENT '是否转基因',
    ADD COLUMN `vector_task_code` varchar(255) NULL COMMENT '实施方案编号',
    ADD COLUMN `experiment_num` varchar(64) NULL COMMENT '试验方案编号',
    ADD COLUMN `project_code` varchar(255) NULL COMMENT '项目号',
    ADD COLUMN `father_single_num` varchar(64) NULL COMMENT '父本单株编号',
    ADD COLUMN `mather_single_num` varchar(64) NULL COMMENT '母本单株编号',
    ADD COLUMN `pd_implement_code` varchar(32) NULL COMMENT 'PD号';

ALTER TABLE `seed_stock_out_log`
    ADD COLUMN `plant_code` varchar(64) NULL COMMENT '种植编号',
    ADD COLUMN `parent_num` varchar(64) NULL COMMENT '上一代种子编号',
    ADD COLUMN `father_info` varchar(255) NULL COMMENT '父本信息',
    ADD COLUMN `mather_info` varchar(255) NULL COMMENT '母本信息',
    ADD COLUMN `generation` varchar(16) NULL COMMENT '代次',
    ADD COLUMN `species_code` varchar(64) NULL COMMENT '项目物种',
    ADD COLUMN `breed_code` varchar(64) NULL COMMENT '品种',
    ADD COLUMN `pollination_method` varchar(255) NULL COMMENT '授粉方式',
    ADD COLUMN `harvest_type` varchar(255) NULL COMMENT '收获方式',
    ADD COLUMN `harvest_time` varchar(16) NULL COMMENT '收获时间',
    ADD COLUMN `source_type` varchar(8) NULL COMMENT '种子来源',
    ADD COLUMN `production_location_code` varchar(255) NULL COMMENT '生产地点',
    ADD COLUMN `stock_location_num` varchar(255) NULL COMMENT '库位编号',
    ADD COLUMN `total_number` decimal(10,2) NULL COMMENT '入库时数量',
    ADD COLUMN `target_character` text NULL COMMENT '目标性状',
    ADD COLUMN `alias_name` varchar(255) NULL COMMENT '别名',
    ADD COLUMN `gene_type` varchar(255) NULL COMMENT '基因型',
    ADD COLUMN `material_type` varchar(255) NULL COMMENT '材料类型',
    ADD COLUMN `mather_seed_num` varchar(32) NULL COMMENT '母本种子编号',
    ADD COLUMN `father_seed_num` varchar(32) NULL COMMENT '父本种子编号',
    ADD COLUMN `mather_region_num` varchar(32) NULL COMMENT '母本小区编号',
    ADD COLUMN `father_region_num` varchar(32) NULL COMMENT '父本小区编号',
    ADD COLUMN `genealogy` varchar(255) NULL COMMENT '系谱',
    ADD COLUMN `gene_separate_flag` varchar(255) NULL COMMENT '是否基因分离',
    ADD COLUMN `trans_flag` varchar(255) NULL COMMENT '是否转基因',
    ADD COLUMN `vector_task_code` varchar(255) NULL COMMENT '实施方案编号',
    ADD COLUMN `experiment_num` varchar(64) NULL COMMENT '试验方案编号',
    ADD COLUMN `project_code` varchar(255) NULL COMMENT '项目号',
    ADD COLUMN `father_single_num` varchar(64) NULL COMMENT '父本单株编号',
    ADD COLUMN `mather_single_num` varchar(64) NULL COMMENT '母本单株编号',
    ADD COLUMN `pd_implement_code` varchar(32) NULL COMMENT 'PD号',
    ADD COLUMN `stock_before_number` decimal(10,2) NULL COMMENT '出库前库存数量',
    ADD COLUMN `stock_after_number` decimal(10,2) NULL COMMENT '出库后库存数量';

ALTER TABLE `seed_stock_destruction_log`
    ADD COLUMN `plant_code` varchar(64) NULL COMMENT '种植编号',
    ADD COLUMN `parent_num` varchar(64) NULL COMMENT '上一代种子编号',
    ADD COLUMN `father_info` varchar(255) NULL COMMENT '父本信息',
    ADD COLUMN `mather_info` varchar(255) NULL COMMENT '母本信息',
    ADD COLUMN `generation` varchar(16) NULL COMMENT '代次',
    ADD COLUMN `species_code` varchar(64) NULL COMMENT '项目物种',
    ADD COLUMN `breed_code` varchar(64) NULL COMMENT '品种',
    ADD COLUMN `pollination_method` varchar(255) NULL COMMENT '授粉方式',
    ADD COLUMN `harvest_type` varchar(255) NULL COMMENT '收获方式',
    ADD COLUMN `harvest_time` varchar(16) NULL COMMENT '收获时间',
    ADD COLUMN `source_type` varchar(8) NULL COMMENT '种子来源',
    ADD COLUMN `production_location_code` varchar(255) NULL COMMENT '生产地点',
    ADD COLUMN `stock_location_num` varchar(255) NULL COMMENT '库位编号',
    ADD COLUMN `total_number` decimal(10,2) NULL COMMENT '入库时数量',
    ADD COLUMN `target_character` text NULL COMMENT '目标性状',
    ADD COLUMN `alias_name` varchar(255) NULL COMMENT '别名',
    ADD COLUMN `gene_type` varchar(255) NULL COMMENT '基因型',
    ADD COLUMN `material_type` varchar(255) NULL COMMENT '材料类型',
    ADD COLUMN `mather_seed_num` varchar(32) NULL COMMENT '母本种子编号',
    ADD COLUMN `father_seed_num` varchar(32) NULL COMMENT '父本种子编号',
    ADD COLUMN `mather_region_num` varchar(32) NULL COMMENT '母本小区编号',
    ADD COLUMN `father_region_num` varchar(32) NULL COMMENT '父本小区编号',
    ADD COLUMN `genealogy` varchar(255) NULL COMMENT '系谱',
    ADD COLUMN `gene_separate_flag` varchar(255) NULL COMMENT '是否基因分离',
    ADD COLUMN `trans_flag` varchar(255) NULL COMMENT '是否转基因',
    ADD COLUMN `vector_task_code` varchar(255) NULL COMMENT '实施方案编号',
    ADD COLUMN `experiment_num` varchar(64) NULL COMMENT '试验方案编号',
    ADD COLUMN `project_code` varchar(255) NULL COMMENT '项目号',
    ADD COLUMN `father_single_num` varchar(64) NULL COMMENT '父本单株编号',
    ADD COLUMN `mather_single_num` varchar(64) NULL COMMENT '母本单株编号',
    ADD COLUMN `pd_implement_code` varchar(32) NULL COMMENT 'PD号',
    ADD COLUMN `stock_before_number` decimal(10,2) NULL COMMENT '销毁前库存数量',
    ADD COLUMN `stock_after_number` decimal(10,2) NULL COMMENT '销毁后库存数量';

-- 如果前面的 ALTER TABLE 已经执行过且 species_code 仍为 varchar(16)，执行下面修正字段长度。
ALTER TABLE `seed_stock_in_log`
    MODIFY COLUMN `species_code` varchar(64) NULL COMMENT '项目物种';

ALTER TABLE `seed_stock_out_log`
    MODIFY COLUMN `species_code` varchar(64) NULL COMMENT '项目物种';

ALTER TABLE `seed_stock_destruction_log`
    MODIFY COLUMN `species_code` varchar(64) NULL COMMENT '项目物种';
