package com.bio.drqi.bsm.kd.enums;

public enum OperateEnum {
    brandSave ,
    brandModify,
    brandDisable,
    brandQuery,
    projectSave,
    projectModify,
    projectDisable,
    stockSave,
    stockQuery,
    stockModify,
    stockDisable,
    materialSave,
    materialModify,
    materialQuery,
    materialDisable,
    groupSave,
    groupQuery,
    inStockSave,
    outStockSave,
    returnStockSave,
    moveStockSave,
}
