ARG BASE_IMAGE=nacos/nacos-server:v2.3.2
FROM ${BASE_IMAGE}

WORKDIR /app

COPY target/bio-drqi-admin-1.0-SNAPSHOT.jar /app/app.jar

ENV TZ=Asia/Shanghai
ENV SERVER_PORT=18093
ENV DEBUG_PORT=28093
ENV JAVA_OPTS="-Xmx1g -Xms1g -Xmn512m -Xss256k"

EXPOSE 18093 28093

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${DEBUG_PORT} -jar /app/app.jar"]
