insert into ai_tool_definition
(tool_code, tool_name, description, tool_type, target_code, input_schema, output_schema, service_url, http_method, risk_level, read_only, status)
values
('query_project_list', '查询项目', '查询项目列表，支持项目编码、项目名称、状态、时间范围等条件。', 'API', 'query_project_list',
 '{"type":"object","properties":{"keyword":{"type":"string","description":"项目编码或关键词"},"projectCode":{"type":"string","description":"项目编码"},"projectName":{"type":"string","description":"项目名称"},"status":{"type":"string","description":"项目状态"},"beginDate":{"type":"string","description":"开始日期"},"endDate":{"type":"string","description":"结束日期"},"pageNum":{"type":"integer"},"pageSize":{"type":"integer"}}}',
 '{"type":"object","properties":{"resultType":{"type":"string"},"answer":{"type":"string"},"table":{"type":"object"}}}',
 '/ai/tool/manage/project/query', 'POST', 'LOW', 1, 'ACTIVE'),
('query_implementation_plan_list', '查询实施方案', '查询实施方案列表，支持实施方案编码、项目编码、子项目编码、任务号、物种等条件。', 'API', 'query_implementation_plan_list',
 '{"type":"object","properties":{"keyword":{"type":"string","description":"实施方案编码或关键词"},"vectorTaskCode":{"type":"string","description":"实施方案编码"},"projectCode":{"type":"string","description":"项目编码"},"subProjectCode":{"type":"string","description":"子项目编码"},"taskNum":{"type":"string","description":"任务号"},"speciesCode":{"type":"string","description":"物种编码"},"breedCode":{"type":"string","description":"品种编码"},"status":{"type":"string","description":"状态"},"pageNum":{"type":"integer"},"pageSize":{"type":"integer"}}}',
 '{"type":"object","properties":{"resultType":{"type":"string"},"answer":{"type":"string"},"table":{"type":"object"}}}',
 '/ai/tool/manage/implementation-plan/query', 'POST', 'LOW', 1, 'ACTIVE'),
('query_transform_list', '查询转化', '查询转化列表，支持转化编码、实施方案编码、项目编码、任务号、物种等条件。', 'API', 'query_transform_list',
 '{"type":"object","properties":{"keyword":{"type":"string","description":"转化编码或关键词"},"transformCode":{"type":"string","description":"转化编码"},"vectorTaskCode":{"type":"string","description":"实施方案编码"},"projectCode":{"type":"string","description":"项目编码"},"subProjectCode":{"type":"string","description":"子项目编码"},"taskNum":{"type":"string","description":"任务号"},"speciesCode":{"type":"string","description":"物种编码"},"pageNum":{"type":"integer"},"pageSize":{"type":"integer"}}}',
 '{"type":"object","properties":{"resultType":{"type":"string"},"answer":{"type":"string"},"table":{"type":"object"}}}',
 '/ai/tool/manage/transform/query', 'POST', 'LOW', 1, 'ACTIVE'),
('query_sample_test_list', '查询取样检测', '查询取样检测列表，支持样品编码、申请单号、实施方案编码、转化编码、种子编号等条件。', 'API', 'query_sample_test_list',
 '{"type":"object","properties":{"keyword":{"type":"string","description":"样品编码或关键词"},"sampleCode":{"type":"string","description":"样品编码"},"applyNo":{"type":"string","description":"申请单号"},"vectorTaskCode":{"type":"string","description":"实施方案编码"},"transformCode":{"type":"string","description":"转化编码"},"seedNum":{"type":"string","description":"种子编号"},"status":{"type":"string","description":"检测结果"},"pageNum":{"type":"integer"},"pageSize":{"type":"integer"}}}',
 '{"type":"object","properties":{"resultType":{"type":"string"},"answer":{"type":"string"},"table":{"type":"object"}}}',
 '/ai/tool/manage/sample-test/query', 'POST', 'LOW', 1, 'ACTIVE'),
('query_plant_list', '查询种植', '查询种植列表，支持种植申请号、实施方案编码、生产实施编码、物种、试验类型等条件。', 'API', 'query_plant_list',
 '{"type":"object","properties":{"keyword":{"type":"string","description":"种植申请号或关键词"},"plantApplyNum":{"type":"string","description":"种植申请号"},"vectorTaskCode":{"type":"string","description":"实施方案编码"},"pdImplementCode":{"type":"string","description":"生产实施编码"},"speciesCode":{"type":"string","description":"物种编码"},"experimentType":{"type":"string","description":"试验类型"},"pageNum":{"type":"integer"},"pageSize":{"type":"integer"}}}',
 '{"type":"object","properties":{"resultType":{"type":"string"},"answer":{"type":"string"},"table":{"type":"object"}}}',
 '/ai/tool/manage/plant/query', 'POST', 'LOW', 1, 'ACTIVE'),
('query_seed_stock_list', '查询种子库', '查询种子库列表，支持种子编号、项目编码、实施方案编码、生产实施编码、物种、品种、世代等条件。', 'API', 'query_seed_stock_list',
 '{"type":"object","properties":{"keyword":{"type":"string","description":"种子编号或关键词"},"seedNum":{"type":"string","description":"种子编号"},"projectCode":{"type":"string","description":"项目编码"},"vectorTaskCode":{"type":"string","description":"实施方案编码"},"pdImplementCode":{"type":"string","description":"生产实施编码"},"speciesCode":{"type":"string","description":"物种编码"},"breedCode":{"type":"string","description":"品种编码"},"seedType":{"type":"string","description":"种子类型"},"generation":{"type":"string","description":"世代"},"beginDate":{"type":"string","description":"开始日期"},"endDate":{"type":"string","description":"结束日期"},"pageNum":{"type":"integer"},"pageSize":{"type":"integer"}}}',
 '{"type":"object","properties":{"resultType":{"type":"string"},"answer":{"type":"string"},"table":{"type":"object"}}}',
 '/ai/tool/manage/seed-stock/query', 'POST', 'LOW', 1, 'ACTIVE')
on duplicate key update
    tool_name = values(tool_name),
    description = values(description),
    tool_type = values(tool_type),
    target_code = values(target_code),
    input_schema = values(input_schema),
    output_schema = values(output_schema),
    service_url = values(service_url),
    http_method = values(http_method),
    risk_level = values(risk_level),
    read_only = values(read_only),
    status = values(status),
    update_time = current_timestamp;
